### PR TITLE
add nightmode to set setConfig

### PR DESCRIPTION
**Pull request by elmissouri16**

### CODE REVIEW

**Comment by JideGuru** [comment]
Is it possible for you to add this to the ios par too?

**Comment by elmissouri16** [comment]
> Is it possible for you to add this to the ios par too?

i don't know how , and even if want to try I don't have a mac to build the app to test with, so its not possible for me

**Comment by JideGuru** [comment]
Okay thanks. I'll work on that then merge the PR

**Comment by elmissouri16** [comment]
> Okay thanks. I'll work on that then merge the PR

awesome thanks I appreciate it

**Review by JideGuru — APPROVED** [review]

**Pull request merged**
